#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user.

# Replace the default Nginx configuration
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf

# Restart Nginx
service nginx restart

# Check Nginx process status
ps auxff | pgrep '[n]ginx'

# Check if Nginx is listening on port 8080
nc -z 0 8080
