#!/usr/bin/env bash
# Short and sweet script to configure Nginx to run as the nginx user on port 8080.

sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sed -i '/:80/a \\tserver_tokens off;' /etc/nginx/nginx.conf
sed -i '/:80/i \\n\taccess_log \/var\/log\/nginx\/access.log;\n\terror_log \/var\/log\/nginx\/error.log;' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
