#!/usr/bin/env bash
# Bash script to install and configure HAproxy on lb-01

# Install HAproxy
sudo apt-get update -y
sudo apt-get install -y haproxy

# Configure HAproxy to send traffic to web-01 and web-02
echo "frontend eadewusic_frontend
    bind *:80
    mode http
    default_backend eadewusic_backend

backend eadewusic_backend
    mode http
    balance roundrobin
    server 5780-web-01 54.90.247.75:80 check
    server 5780-web-02 52.200.5.159:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

# Restart HAproxy to apply the changes
sudo service haproxy restart

# Verify HAproxy status and check if the output contains "web-01"
status=$(sudo service haproxy status)
if [[ "$status" == *"web-01"* ]]; then
    echo "HAproxy installation and configuration successful!"
else
    echo "Error: HAproxy configuration failed."
fi
